### ISSUE TITLE
IslandUtils 1.6.10 incompatible with Noxesium 2.3.1

### ISSUE THREAD

**Issue by SuperNeon4ik** [AsoDesu/IslandUtils#155]
**Describe the bug**
New Noxesium version 2.3.1 has renamed a variable, which IslandUtils depends on, resulting in a crash, thus it being incompatible with the current version of IslandUtils (1.6.10).

**To Reproduce**
Steps to reproduce the behaviour:
1. Install latest version of IslandUtils (1.6.10) & Noxesium (2.3.1)
2. Attempt to launch Minecraft
3. See crash

**Expected behaviour**
Game shouldn't crash.

**Screenshots & Logs**
```log
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2024-09-25 21:31:23
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'islandutils'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchFieldError: Class com.noxcrew.noxesium.network.NoxesiumPackets does not have member field 'com.noxcrew.noxesium.network.NoxesiumPayloadType MCC_SERVER'
	at net.asodev.islandutils.modules.NoxesiumIntegration.init(NoxesiumIntegration.java:14)
	at net.asodev.islandutils.IslandUtilsClient.onInitializeClient(IslandUtilsClient.java:60)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 9 more
```

**System & Version Information**
-   Java Version: Java 21.0.4
-   Minecraft Version: 1.21
-   IslandUtils Version: 1.6.10
-   OS: Arch Linux (Wayland)
-   CPU: Intel i7-14700F

**Comment by thehamish555** [comment]
sorry to have this reopened, just wanted to ask if a build/release could be made with these changes? (also assuming they work for Noxesium 2.3.3)
