### ISSUE TITLE
Discord Presence

### ISSUE THREAD

**Issue by JoshM-Dev** [AsoDesu/IslandUtils#61]
**Describe the bug**
When enabling the discord presence feature whilst on MCCI it crashes my whole game and whilst not on MCCI, it doesn't let me join. I'm on a Mac.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable Discord Presence
2. Join the server

**Expected behaviour**
I should be able to join and have the discord presence

**Screenshots & Logs**
![image](https://github.com/AsoDesu/IslandUtils/assets/67236442/407c9b37-2fbe-4b7a-8d8b-c265f68dd7db)

**System & Version Information**
 - Java Version: [e.g. Java 17]
- Minecraft Version: 1.19.4
- IslandUtils Version: 1.4.4
- OS: MacOS
- CPU: 4x Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz

**Comment by AsoDesu** [comment]
Can you send me a log file?

**Comment by JOSH-Configs** [comment]
Log file contains my name, etc. but this is the discord error:
[16:37:37] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:545) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1238) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: dlsym(0x0, DiscordCreate): invalid handle
	at de.jcm.discordgamesdk.Core.create(Native Method) ~[com_github_jncrmx_discord-game-sdk4j-v0.5.5-dc1a9a49fb6da66a.jar:?]
	at de.jcm.discordgamesdk.Core.<init>(Core.java:436) ~[com_github_jncrmx_discord-game-sdk4j-v0.5.5-dc1a9a49fb6da66a.jar:?]
	at net.asodev.islandutils.discord.DiscordPresence.init(DiscordPresence.java:39) ~[islandutils-1.4.4+1.19.4.jar:?]
	at net.asodev.islandutils.discord.DiscordPresenceUpdator.create(DiscordPresenceUpdator.java:27) ~[islandutils-1.4.4+1.19.4.jar:?]
	at net.asodev.islandutils.discord.DiscordPresenceUpdator.updateFromConfig(DiscordPresenceUpdator.java:184) ~[islandutils-1.4.4+1.19.4.jar:?]
	at net.asodev.islandutils.IslandUtils.lambda$onInitialize$0(IslandUtils.java:33) ~[islandutils-1.4.4+1.19.4.jar:?]
	at me.shedaniel.autoconfig.ConfigManager.save(ConfigManager.java:75) ~[cloth-config-api.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.save(AbstractConfigScreen.java:182) ~[cloth-config-api.jar:?]
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.save(ClothConfigScreen.java:319) ~[cloth-config-api.jar:?]
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.saveAll(AbstractConfigScreen.java:172) ~[cloth-config-api.jar:?]
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.lambda$init$3(ClothConfigScreen.java:133) ~[cloth-config-api.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:187) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.method_25402(AbstractConfigScreen.java:263) ~[cloth-config-api.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:540) ~[client-intermediary.jar:?]
	... 16 more

**Comment by AsoDesu** [comment]
Okay thank you, i will look into this :D
